import React, { useEffect, useState, useRef } from 'react';
import { motion } from 'framer-motion';
import { payrollAPI } from '../../services/api';
import { format } from 'date-fns';
import { Download, FileText } from 'lucide-react';
import toast from 'react-hot-toast';
import { useAuth } from '../../context/AuthContext';

const MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

export default function PayrollPage() {
  const { user } = useAuth();
  const [records, setRecords] = useState([]);
  const [current, setCurrent] = useState(null);
  const [loading, setLoading] = useState(true);
  const [selectedMonth, setSelectedMonth] = useState(null);
  const slipRef = useRef(null);

  useEffect(() => {
    payrollAPI.getMy()
      .then(r => { setRecords(r.data.records || []); setCurrent(r.data.currentMonth); setSelectedMonth(r.data.currentMonth); })
      .catch(() => toast.error('Failed to load payroll'))
      .finally(() => setLoading(false));
  }, []);

  const handleDownload = async () => {
    if (!selectedMonth) return;
    const { default: jsPDF } = await import('jspdf');
    const doc = new jsPDF({ unit: 'pt', format: 'a4' });
    const emp = user?.employee;

    // Header
    doc.setFillColor(79, 70, 229);
    doc.rect(0, 0, 595, 80, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22); doc.setFont('helvetica', 'bold');
    doc.text('DAYFLOW', 40, 48);
    doc.setFontSize(10); doc.setFont('helvetica', 'normal');
    doc.text('Salary Slip', 40, 66);
    doc.text(`${MONTHS[selectedMonth.month - 1]} ${selectedMonth.year}`, 480, 48, { align: 'right' });

    // Employee Info
    doc.setTextColor(15, 17, 23);
    doc.setFontSize(11); doc.setFont('helvetica', 'bold');
    doc.text(`${emp?.firstName || ''} ${emp?.lastName || ''}`, 40, 110);
    doc.setFontSize(9); doc.setFont('helvetica', 'normal'); doc.setTextColor(100, 116, 139);
    doc.text(`${emp?.employeeCode || ''}  ·  ${user?.email || ''}`, 40, 126);

    // Earnings table
    doc.setTextColor(15, 17, 23);
    let y = 160;
    const col1 = 40, col2 = 300, col3 = 500;

    // Section headers
    doc.setFillColor(241, 245, 249);
    doc.rect(40, y - 14, 515, 20, 'F');
    doc.setFontSize(9); doc.setFont('helvetica', 'bold'); doc.setTextColor(79, 70, 229);
    doc.text('EARNINGS', col1, y); doc.text('DEDUCTIONS', col2, y); y += 26;

    const earnings = [
      ['Basic Salary', selectedMonth.basicSalary],
      ['HRA', selectedMonth.hra],
      ['Transport', selectedMonth.transport],
      ['Other Allowance', selectedMonth.otherAllowance],
    ];
    const deductions = [
      ['PF Deduction', selectedMonth.pfDeduction],
      ['Tax Deduction', selectedMonth.taxDeduction],
      ['Other Deductions', selectedMonth.otherDeductions],
    ];

    doc.setFont('helvetica', 'normal'); doc.setTextColor(51, 65, 85); doc.setFontSize(9);
    const maxRows = Math.max(earnings.length, deductions.length);
    for (let i = 0; i < maxRows; i++) {
      if (earnings[i]) { doc.text(earnings[i][0], col1, y); doc.text(`Rs. ${parseFloat(earnings[i][1] || 0).toLocaleString('en-IN')}`, col2 - 20, y, { align: 'right' }); }
      if (deductions[i]) { doc.text(deductions[i][0], col2, y); doc.text(`Rs. ${parseFloat(deductions[i][1] || 0).toLocaleString('en-IN')}`, col3, y, { align: 'right' }); }
      y += 22;
    }

    // Net Salary
    y += 10;
    doc.setFillColor(79, 70, 229);
    doc.rect(40, y, 515, 40, 'F');
    doc.setTextColor(255, 255, 255); doc.setFont('helvetica', 'bold'); doc.setFontSize(13);
    doc.text('NET SALARY', 60, y + 25);
    doc.text(`Rs. ${parseFloat(selectedMonth.netSalary || 0).toLocaleString('en-IN')}`, 540, y + 25, { align: 'right' });

    // Footer
    doc.setFontSize(8); doc.setFont('helvetica', 'normal'); doc.setTextColor(148, 163, 184);
    doc.text('This is a computer-generated document. No signature required.', 295, 780, { align: 'center' });
    doc.text('Generated by DAYFLOW — The Human Operating System', 295, 795, { align: 'center' });

    doc.save(`DAYFLOW_Salary_Slip_${MONTHS[selectedMonth.month - 1]}_${selectedMonth.year}.pdf`);
    toast.success('Salary slip downloaded!');
  };

  if (loading) return <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: 300 }}><div className="spinner spinner-lg" /></div>;

  const fm = (v) => `₹${parseFloat(v || 0).toLocaleString('en-IN')}`;

  return (
    <div className="animate-fadeIn">
      <div className="topbar">
        <div>
          <h1 className="page-title">Payroll</h1>
          <p className="page-subtitle">Your compensation breakdown</p>
        </div>
        <button className="btn btn-primary" onClick={handleDownload} disabled={!selectedMonth}>
          <Download size={15} /> Download Slip
        </button>
      </div>

      {/* Month selector */}
      <div style={{ display: 'flex', gap: 10, marginBottom: 24, flexWrap: 'wrap' }}>
        {records.map(r => (
          <button key={r.id} onClick={() => setSelectedMonth(r)}
            className={`btn btn-sm ${selectedMonth?.id === r.id ? 'btn-primary' : 'btn-secondary'}`}>
            {MONTHS[r.month - 1]} {r.year}
          </button>
        ))}
      </div>

      {selectedMonth ? (
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20 }}>
          {/* Earnings */}
          <div className="card">
            <h3 style={{ color: 'var(--success)', marginBottom: 16 }}>💰 Earnings</h3>
            {[
              { label: 'Basic Salary', value: selectedMonth.basicSalary },
              { label: 'HRA', value: selectedMonth.hra },
              { label: 'Transport Allowance', value: selectedMonth.transport },
              { label: 'Other Allowance', value: selectedMonth.otherAllowance },
            ].map(row => (
              <div key={row.label} style={{ display: 'flex', justifyContent: 'space-between', padding: '10px 0', borderBottom: '1px solid var(--surface-2)' }}>
                <span style={{ color: 'var(--text-secondary)', fontSize: '0.875rem' }}>{row.label}</span>
                <span style={{ fontWeight: 600 }}>{fm(row.value)}</span>
              </div>
            ))}
            <div style={{ display: 'flex', justifyContent: 'space-between', padding: '12px 0', fontWeight: 700, color: 'var(--success)' }}>
              <span>Gross Total</span>
              <span>{fm(selectedMonth.grossSalary)}</span>
            </div>
          </div>

          {/* Deductions + Net */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
            <div className="card">
              <h3 style={{ color: 'var(--danger)', marginBottom: 16 }}>📉 Deductions</h3>
              {[
                { label: 'PF (12%)', value: selectedMonth.pfDeduction },
                { label: 'Tax (TDS)', value: selectedMonth.taxDeduction },
                { label: 'Other', value: selectedMonth.otherDeductions },
              ].map(row => (
                <div key={row.label} style={{ display: 'flex', justifyContent: 'space-between', padding: '10px 0', borderBottom: '1px solid var(--surface-2)' }}>
                  <span style={{ color: 'var(--text-secondary)', fontSize: '0.875rem' }}>{row.label}</span>
                  <span style={{ fontWeight: 600, color: 'var(--danger)' }}>- {fm(row.value)}</span>
                </div>
              ))}
            </div>

            <motion.div className="card" style={{ background: 'var(--brand-gradient)', border: 'none', textAlign: 'center', padding: 'var(--sp-8)' }}>
              <div style={{ fontSize: '0.75rem', color: 'rgba(255,255,255,0.7)', textTransform: 'uppercase', letterSpacing: '0.1em', marginBottom: 8 }}>Net Take-Home</div>
              <motion.div
                initial={{ scale: 0.8, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                transition={{ type: 'spring', stiffness: 300, damping: 20 }}
                style={{ fontSize: '2.5rem', fontWeight: 900, color: '#fff' }}
              >
                {fm(selectedMonth.netSalary)}
              </motion.div>
              <div style={{ fontSize: '0.8rem', color: 'rgba(255,255,255,0.6)', marginTop: 6 }}>
                {MONTHS[selectedMonth.month - 1]} {selectedMonth.year}
              </div>
            </motion.div>
          </div>
        </div>
      ) : (
        <div className="empty-state"><div className="empty-state-icon"><FileText /></div><div className="empty-state-title">No payroll data</div></div>
      )}
    </div>
  );
}
